name: Keep Alive

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: # Allow manual triggering for testing

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Request
        run: curl https://itu-r1qa.onrender.com/health
